version: '3.8'
services:
  glpi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - glpi-data:/glpi-data
    environment:
      - MYSQL_HOST=db   # Using the service name 'db' as the hostname
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=glpipassword
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - glpi-network  # Connects to the custom network 'glpi-network'

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: glpi
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpipassword
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - glpi-network  # Connects to the custom network 'glpi-network'

volumes:
  glpi-data:
  db-data:

networks:
  glpi-network:  # Define a custom network called 'glpi-network'
    driver: bridge  # Using the bridge driver for custom network
